import type { Page } from "@playwright/test";
import { test, expect } from "./protected-fixtures";
const key = "safi-burger-v1";
async function login(page: Page, name = "Alex") { await page.goto("/login"); await page.getByRole("button", { name: `Continue as ${name}`, exact: true }).click(); }
async function addClassic(page: Page) { await page.goto("/menu"); await page.getByRole("article").filter({ has: page.getByRole("heading", { name: "The House Classic", exact: true }) }).getByRole("button", { name: "Add to bag" }).click(); }
async function pay(page: Page) { await page.goto("/checkout"); await page.getByRole("checkbox").check(); await page.getByRole("button", { name: /Confirm demo payment/ }).click(); await expect(page).toHaveURL(/\/orders$/); }
test.beforeEach(async ({ page }) => {
  await page.route("https://images.unsplash.com/**", route => route.abort());
  await page.route("https://fonts.googleapis.com/**", route => route.abort());
  await page.goto("/"); await page.evaluate(() => localStorage.clear()); await page.reload();
});
test("home navigation and photography fallback", async ({ page }) => { await expect(page.getByRole("heading", { name: /Your new happy place/ })).toBeVisible(); await expect(page.getByRole("img", { name: /Juicy cheeseburger/ })).toBeVisible(); await page.getByRole("link", { name: "Explore the menu" }).click(); await expect(page).toHaveURL(/\/menu$/); });
test("search, categories, unavailable items", async ({ page }) => { await page.goto("/menu"); await page.getByRole("textbox", { name: "Search menu" }).fill("Golden"); await expect(page.getByRole("article")).toHaveCount(1); await page.getByRole("textbox", { name: "Search menu" }).fill(""); await page.getByRole("button", { name: "Drinks", exact: true }).click(); await expect(page.getByRole("article")).toHaveCount(1); await page.getByRole("button", { name: "All", exact: true }).click(); await expect(page.getByRole("button", { name: "Currently unavailable" })).toBeDisabled(); });
test("bag quantities, removal, reload persistence", async ({ page }) => { await addClassic(page); await page.goto("/cart"); await page.getByRole("button", { name: "Increase The House Classic" }).click(); await expect(page.getByText("$21.80", { exact: true }).first()).toBeVisible(); await page.reload(); await expect(page.getByText("$21.80", { exact: true }).first()).toBeVisible(); await page.getByRole("button", { name: "Decrease The House Classic" }).click(); await page.getByRole("button", { name: "Remove The House Classic" }).click(); await expect(page.getByRole("heading", { name: "Something delicious belongs here." })).toBeVisible(); });
test("guest checkout requires demo login", async ({ page }) => { await addClassic(page); await page.goto("/checkout"); await expect(page).toHaveURL(/\/login$/); });
test("demo consent, one order and customer isolation", async ({ page }) => { await login(page); await addClassic(page); await page.goto("/checkout"); await expect(page.getByRole("button", { name: /Confirm demo payment/ })).toBeDisabled(); await pay(page); await expect(page.getByText("Demo payment confirmed")).toHaveCount(1); await page.reload(); await expect(page.getByText("Demo payment confirmed")).toHaveCount(1); await login(page, "Jamie"); await page.goto("/orders"); await expect(page.getByText("Demo payment confirmed")).toHaveCount(0); await login(page); await page.goto("/orders"); await expect(page.getByText("Demo payment confirmed")).toHaveCount(1); });
test("customer management denied and signout", async ({ page }) => { await login(page); await page.goto("/manage/menu"); await expect(page.getByText("Menu management is available to managers and owners.")).toBeVisible(); await page.goto("/login"); await page.getByRole("button", { name: "Sign out", exact: true }).click(); await page.goto("/orders"); await expect(page).toHaveURL(/\/login$/); });
for (const name of ["Sam", "Robin"]) test(`${name} can create and edit menu items`, async ({ page }) => {
  await login(page, name); await page.getByRole("button", { name: "Create menu item" }).click();
  const dialog = page.getByRole("dialog"); await dialog.getByLabel("Name", { exact: true }).fill("Test Burger"); await dialog.getByLabel("Description").fill("A deterministic fixture item"); await dialog.getByLabel("Price (USD)").fill("8.25"); await dialog.getByRole("button", { name: "Save menu item" }).click();
  await page.getByRole("button", { name: "Edit Test Burger" }).click(); await dialog.getByLabel("Price (USD)").fill("-1"); await dialog.getByRole("button", { name: "Save menu item" }).click(); await expect(dialog.getByRole("alert")).toBeVisible(); await dialog.getByLabel("Price (USD)").fill("9.50"); await dialog.getByRole("checkbox").uncheck(); await dialog.getByRole("button", { name: "Save menu item" }).click(); await page.reload(); const item = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Test Burger" }) }); await expect(item.getByText("Unavailable", { exact: true })).toBeVisible(); await expect(item.getByText(/\$9.50/)).toBeVisible();
});
test("checkout rejects menu price and availability changes", async ({ page }) => {
  await login(page); await addClassic(page);
  await page.evaluate(storageKey => { const s = JSON.parse(localStorage.getItem(storageKey)!); s.menu.find((i: { id: string }) => i.id === "classic").price = 1200; localStorage.setItem(storageKey, JSON.stringify(s)); }, key);
  await page.goto("/checkout"); await expect(page.getByRole("alert")).toContainText("new price"); await expect(page.getByRole("button", { name: /Confirm demo payment/ })).toBeDisabled();
  await page.evaluate(storageKey => { const s = JSON.parse(localStorage.getItem(storageKey)!); s.menu.find((i: { id: string }) => i.id === "classic").available = false; localStorage.setItem(storageKey, JSON.stringify(s)); }, key);
  await page.reload(); await expect(page.getByRole("alert")).toContainText("unavailable");
});
test("corrupt and invalid storage recover to stable seeds", async ({ page }) => { for (const value of ["{broken", JSON.stringify({ version: 99 }), JSON.stringify({ version: 1, menu: [], cart: [{ quantity: -1 }] })]) { await page.evaluate(([storageKey, raw]) => localStorage.setItem(storageKey, raw), [key, value]); await page.goto("/menu"); await expect(page.getByRole("article")).toHaveCount(6); } });
test("reset clears persisted demo data", async ({ page }) => { await login(page); await addClassic(page); page.once("dialog", dialog => dialog.accept()); await page.getByRole("button", { name: "Reset demo" }).click(); await page.goto("/cart"); await expect(page.getByRole("heading", { name: "Something delicious belongs here." })).toBeVisible(); await page.goto("/orders"); await expect(page).toHaveURL(/\/login$/); });
