import { Link } from "react-router-dom";
import { Minus, Plus, ShoppingBag, Trash2, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FoodImage } from "@/components/burger/ProductCard";
import { money } from "@/lib/burger/domain";
import { useShop, reportError } from "@/lib/burger/store";
export default function Cart() {
  const { state, quantity, total, cartIssues } = useShop();
  const change = (id: string, count: number) => { try { quantity(id, count); } catch (e) { reportError(e); } };
  return <section className="page-wrap"><p className="eyebrow">Good choices, all around</p><h1 className="page-title">Your happy bag.</h1>{!state.cart.length ? <div className="mt-8 rounded-3xl border bg-card p-12 text-center"><ShoppingBag className="mx-auto mb-4 text-primary" size={40} /><h2 className="font-display text-2xl font-bold">Something delicious belongs here.</h2><Button asChild className="mt-6 rounded-full"><Link to="/menu">Explore the menu</Link></Button></div> : <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><div className="space-y-4">{cartIssues.map(issue => <p key={issue} role="alert" className="rounded-xl bg-secondary p-4 font-semibold text-primary">{issue}</p>)}{state.cart.map(line => { const item = state.menu.find(i => i.id === line.itemId); return <article key={line.itemId} className="flex flex-wrap items-center gap-4 rounded-2xl border bg-card p-4"><FoodImage src={item?.image ?? ""} alt={item?.name ?? "Removed item"} className="h-24 w-24 rounded-xl object-cover" /><div className="min-w-32 flex-1"><h2 className="font-display text-xl font-bold">{item?.name ?? "Removed item"}</h2><p className="mt-1 text-sm text-muted-foreground">{money(line.price)} each</p></div><div className="flex items-center gap-2 rounded-full border p-1"><Button size="icon" variant="ghost" className="rounded-full" aria-label={`Decrease ${item?.name}`} onClick={() => change(line.itemId, line.quantity - 1)}><Minus size={16} /></Button><span className="w-6 text-center font-bold">{line.quantity}</span><Button size="icon" variant="ghost" className="rounded-full" disabled={line.quantity === 99} aria-label={`Increase ${item?.name}`} onClick={() => change(line.itemId, line.quantity + 1)}><Plus size={16} /></Button></div><strong>{money(line.price * line.quantity)}</strong><Button size="icon" variant="ghost" className="rounded-full text-primary" aria-label={`Remove ${item?.name}`} onClick={() => change(line.itemId, 0)}><Trash2 size={18} /></Button></article>; })}<Link to="/menu" className="inline-block pt-3 text-sm font-semibold text-primary underline">Keep exploring</Link></div><aside className="h-fit rounded-3xl border bg-card p-6"><h2 className="font-display text-2xl font-bold">The good stuff.</h2><div className="mt-6 flex justify-between"><span>Subtotal</span><span>{money(total)}</span></div><div className="mt-3 flex justify-between text-sm text-muted-foreground"><span>Pickup · No fees</span><span>$0.00</span></div><div className="my-6 flex justify-between border-t pt-5 text-xl font-bold"><span>Total</span><span>{money(total)}</span></div><Button asChild={!cartIssues.length} disabled={!!cartIssues.length} className="w-full rounded-full py-6">{cartIssues.length ? <span>Review your bag first</span> : <Link to="/checkout">Checkout <ArrowRight className="ml-2" size={17} /></Link>}</Button><p className="mt-4 text-center text-xs text-muted-foreground">Demo checkout. No money changes hands.</p></aside></div>}</section>;
}
